# Production Configuration for Authway
# Copy this file to config.yaml and fill in your production values

app:
  name: "Authway"
  version: "1.0.0"
  environment: "production"
  port: "8080"
  base_url: "https://auth.yourdomain.com"  # Replace with your actual domain

database:
  host: "postgres"  # Docker service name or production host
  port: 5432
  user: "authway"
  password: "${POSTGRES_PASSWORD}"  # Use environment variable
  name: "authway"
  ssl_mode: "require"  # Enable SSL in production

redis:
  host: "redis"  # Docker service name or production host
  port: 6379
  password: "${REDIS_PASSWORD}"  # Use environment variable if needed
  db: 0

jwt:
  access_token_secret: "${JWT_ACCESS_SECRET}"  # Must be strong random string
  refresh_token_secret: "${JWT_REFRESH_SECRET}"  # Must be strong random string
  access_token_expiry: "15m"
  refresh_token_expiry: "7d"
  issuer: "https://auth.yourdomain.com"  # Replace with your domain
  private_key_path: "/app/certs/jwt-private.pem"  # RSA private key
  public_key_path: "/app/certs/jwt-public.pem"   # RSA public key

oauth:
  authorize_code_expiry: "10m"
  allowed_grant_types: ["authorization_code", "refresh_token"]
  allowed_scopes: ["openid", "profile", "email"]
  require_pkce: true

hydra:
  admin_url: "http://hydra:4445"  # Docker service name or production URL
  public_url: "https://oauth.yourdomain.com"  # Replace with your OAuth domain

cors:
  allowed_origins:
    - "https://yourdomain.com"  # Replace with your frontend domains
    - "https://app.yourdomain.com"

email:
  smtp_host: "${SMTP_HOST}"  # e.g., smtp.gmail.com
  smtp_port: 587
  smtp_user: "${SMTP_USER}"
  smtp_password: "${SMTP_PASSWORD}"
  from_email: "noreply@yourdomain.com"  # Replace with your domain
  from_name: "Authway Authentication"

# Google OAuth Configuration
google:
  enabled: true
  client_id: "${GOOGLE_CLIENT_ID}"  # Get from Google Cloud Console
  client_secret: "${GOOGLE_CLIENT_SECRET}"  # Get from Google Cloud Console
  redirect_url: "https://auth.yourdomain.com/auth/google/callback"  # Replace with your domain