apiVersion: v1
kind: Namespace
metadata:
  name: authway-production
  labels:
    name: authway-production
    environment: production
    managed-by: kubectl
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: authway-resource-quota
  namespace: authway-production
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: authway-limit-range
  namespace: authway-production
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 1Gi
    type: PersistentVolumeClaim